name: Integaration Test Workflow

on:
  pull_request:
    branches: [main]

env:
  PORT: ${{secrets.PORT}}
  DATABASE_NAME: ${{secrets.DATABASE_NAME}}
  DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
  DATABASE_USER: ${{secrets.DATABASE_USER}}
  HOST: ${{secrets.HOST}}
  ENVIRONMENT: ${{secrets.ENVIRONMENT}}
  PUBSUB_TOPIC: ${{secrets.PUBSUB_TOPIC}}
  PUBSUB_SUBSCRIPTION: ${{secrets.PUBSUB_SUBSCRIPTION}}
  DOMAIN: ${{secrets.DOMAIN}}

jobs:
  build:
    name: Integration Test Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to our code
        uses: actions/checkout@v3

      - name: start mysql server already installed in the image
        run: |
          sudo systemctl start mysql.service
          sudo mysql --version

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: npm ci

      - name: "check env"
        run: echo ${{ secrets.DATABASE_NAME }}

      - name: Run Test
        run: npm test
